export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const CONTRACT_INTERACTION = 'CONTRACT_INTERACTION';
export const CONTRACT_INTERACTION_SUCCESS = 'CONTRACT_INTERACTION_SUCCESS'
export const CONTRACT_INTERACTION_ERROR = 'CONTRACT_INTERACTION_ERROR'